config/routes.rb
Rails.application.routes.draw do

  resources :recipes, only: [:index, :show] do
    get :search, on: :collection
  end
  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe
  include HTTParty
  format :json

  base_uri 'http://www.recipepuppy.com/api/'

  def self.search(query)
    get("/?q=#{query}")['results']
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  require 'will_paginate/array'

  def index
    if params['query'].present?
      @recipes = Recipe.search(params['query']).paginate(:page => params[:page], :per_page => 10)

      respond_to do |format|
        format.js
        format.html
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeFinder</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/partials/navbar' %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Recipe Finder</a>
  <div class="navbar-nav">
    <a class="nav-item nav-link active" href="#">Home</a>
  </div>
</nav>

app/views/recipes/_recipes.html.erb
<div class="row padded-top">
    <div class="col-lg-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Ingedients</th>
            <th>Image</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
          <tr>
            <td><%= link_to recipe['title'], recipe['href'], target: '_blank' %></td>
            <td><%= recipe['ingredients'] %></td>
            <td><%= image_tag(recipe['thumbnail']) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= will_paginate @recipes %>

app/views/recipes/_search.html.erb
<%= form_tag(recipes_path, method: :get, remote: :true) do %>
  <div class="input-group">
    <%= text_field_tag 'query', "", class: 'form-control',  placeholder: "Search for..." %>
    <span class="input-group-btn">
      <%= submit_tag 'Search', class: "btn btn-custom" %>
    </span>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div class="row padded-top">
  <div class="col-lg-12">
    <%= render  "search" %>
  </div>
</div>

<div id="recipes">
  <% if @recipes.present? %>
    <%= render  "recipes" %>
  <% end %>
</div>

app/views/recipes/index.js.erb
<% if @recipes.present? %>
  $("#recipes").html("<%= escape_javascript(render partial: 'recipes' ) %>");
<% else %>
  $("#recipes").html("<br><h4>Sorry, there were no results found.</h4>");
<% end %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>